modLoader="javafml"
loaderVersion="[32,)"
license="MIT License"
issueTrackerURL="https://github.com/EwyBoy/CHA-S/issues"
logoFile="icon.png"

[[mods]]
    modId="craftablehorsearmour"
    version="${file.jarVersion}"
    displayName="CHA&S - Craftable Horse Armour and Saddle"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/cha-s"
    credits="You came here for the credits, huh?"
    authors="Ewy"
    description="Read the name of the mod"

[[dependencies.craftablehorsearmour]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.craftablehorsearmour]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16, 1.17)"
    ordering="NONE"
    side="BOTH"
